Fix Python workflow

diff --git a/.github/workflows/python-ci.yml b/.github/workflows/python-ci.yml
--- a/.github/workflows/python-ci.yml
+++ b/.github/workflows/python-ci.yml
@@ -43,12 +43,12 @@ jobs:
         run: |
           # Stop the build if there are Python syntax errors or undefined names
           source venv/bin/activate
-          flake8 --config=.flake8 .
-          black --check .
-          isort --check-only .
+          flake8 --config=.flake8 --exclude=./sycret/sycret/ .
+          black --check . --exclude '/sycret/sycret/*'
+          isort --check-only . -s sycret/sycret/
           # Run type checker in CI such that type errors can be identified and gradually addressed.
           # Once all existing type errors are addressed, the `|| echo` after the mypy call can be removed.
-          mypy src || echo "Type errors found, continuing build..."
+          mypy sycret || echo "Type errors found, continuing build..."
       - name: Check docstring coverage
         run: |
           source venv/bin/activate
